### PR TITLE
Or 1691 thanos event listener deploy GitHub action ci

### PR DESCRIPTION
**Pull request by xxeonge**
Hello everyone!

- added CI  to deploy docker image and update kustomize

- CMD was added to the Dockerfile to run the app.

Thank you : )

### CODE REVIEW

**Review by 0x6e616d — APPROVED** [review]
+1

**Review by rlgns98kr — APPROVED** [review]
Thank you very much, Sia! 🎉🙇🏻‍♂️

**Comment by rlgns98kr** [comment]
@xxeonge 
Will you resolve the CI issue? 🙇🏼‍♂️
There is a trivial problem!
https://github.com/tokamak-network/tokamak-thanos-event-listener/actions/runs/9774288595/job/26982496722

**Comment by rlgns98kr** [comment]
@xxeonge 
Thank you very much! 🙇🏼‍♂️

**Pull request merged**
