### PR TITLE
feat: add unit tests for the event listener service and block keeper

### PR DESCRIPTION
**Pull request by ghost**
I add the unit tests to ensure everything works correctly

- [x] Add `service_test.go` to test the whole event listener
* Test `syncOldBlocks`
* Test `handleReorgBlocks`
- [x] Add `block_keeper_test.go` to test the block keeper
* Test init the keeper with/without the current block hash
* Test `getReorgBlocks`

### CODE REVIEW

**Review by xxeonge — COMMENTED** [review]
Thank you! @0x6e616d
It worked well when i tested it locally 🙌 
@brave left a comment on the previous PR, could you please check it ?? 🙇‍♀️

Thank you!

**Comment by nguyenzung** [comment]
> Thank you! @0x6e616d It worked well when i tested it locally 🙌 @brave left a comment on the previous PR, could you please check it ?? 🙇‍♀️
> 
> Thank you!

Thank you, Sia!

I have an urgent task. I will look at this PR later.

**Comment by 0x6e616d** [comment]
> Thank you! @0x6e616d It worked well when i tested it locally 🙌 @brave left a comment on the previous PR, could you please check it ?? 🙇‍♀️
> 
> Thank you!

Hi Sia, Everything is fixed in the previous PR.

**Review by xxeonge — APPROVED** [review]
Thank you Nam! :))

**Review by nguyenzung — APPROVED** [review]
LGTM!

**Pull request merged**
